from .audio_segment import NODE_CLASS_MAPPINGS as AUDIO_SEGMENT_NODES
from .audio_segment import NODE_DISPLAY_NAME_MAPPINGS as AUDIO_SEGMENT_NAMES
from .coral_asr import NODE_CLASS_MAPPINGS as CORAL_ASR_NODES
from .coral_asr import NODE_DISPLAY_NAME_MAPPINGS as CORAL_ASR_NAMES

NODE_CLASS_MAPPINGS = {**AUDIO_SEGMENT_NODES, **CORAL_ASR_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**AUDIO_SEGMENT_NAMES, **CORAL_ASR_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
