from .audio_resample import NODE_CLASS_MAPPINGS as AUDIO_RESAMPLE_NODES
from .audio_resample import NODE_DISPLAY_NAME_MAPPINGS as AUDIO_RESAMPLE_NAMES
from .audio_segment import NODE_CLASS_MAPPINGS as AUDIO_SEGMENT_NODES
from .audio_segment import NODE_DISPLAY_NAME_MAPPINGS as AUDIO_SEGMENT_NAMES
from .coral_asr import NODE_CLASS_MAPPINGS as CORAL_ASR_NODES
from .coral_asr import NODE_DISPLAY_NAME_MAPPINGS as CORAL_ASR_NAMES
from .speaker_diarization import NODE_CLASS_MAPPINGS as DIARIZATION_NODES
from .speaker_diarization import NODE_DISPLAY_NAME_MAPPINGS as DIARIZATION_NAMES

NODE_CLASS_MAPPINGS = {
    **AUDIO_RESAMPLE_NODES,
    **AUDIO_SEGMENT_NODES,
    **CORAL_ASR_NODES,
    **DIARIZATION_NODES,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **AUDIO_RESAMPLE_NAMES,
    **AUDIO_SEGMENT_NAMES,
    **CORAL_ASR_NAMES,
    **DIARIZATION_NAMES,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
